### ISSUE TITLE
Upgrade QEMU to 8

### ISSUE THREAD

**Issue by pedrolamarao** [pedrolamarao/psys#149]
Initial testing found that Metal tests currently do not interoperate with QEMU newer than 6.0.

**Comment by pedrolamarao** [comment]
I have tested today and found that Metal tests succeed with QEMU from 6.0 to 7.1
Version 7.2 onwards fails with some kind of networking problem.

**Comment by pedrolamarao** [comment]
Also fails with default Ubuntu 22.04  QEMU 6.2.

**Comment by pedrolamarao** [comment]
With QEMU 8.1 for Windows, tests complete with this failure:

```
Caused by: java.net.SocketException: Connection reset
        at br.dev.pedrolamarao.gdb.rsp.GdbRemoteParser.read(GdbRemoteParser.java:36)
        at br.dev.pedrolamarao.gdb.rsp.GdbRemote.exchange(GdbRemote.java:39)
        at MultibootTestImageTask.action(multiboot.kt:417)
```

**Comment by pedrolamarao** [comment]
After #161, works with QEMU up to 7.2.
